### ISSUE TITLE
Get fullDateValidationty to insert errors into ajv error list

### ISSUE THREAD

**Issue by felixMasonJncc** [jncc/catalog#14]
https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#reporting-errors-in-custom-keywords

**Comment by felixMasonJncc** [comment]
Reasses with update to later version of ajb

**Comment by felixMasonJncc** [comment]
Check the posibility of doing this after library update #29

**Comment by felixMasonJncc** [comment]
Depends on case #29

**Comment by LynnHeeley** [comment]
time box morning to investigate
