### ISSUE TITLE
Test count doesn't match in shippable

### ISSUE THREAD

**Issue by felixMasonJncc** [jncc/catalog#18]
The number of tests reported in shippable is less then then number of tests reported by yarn test

There is a line beginning " ./node_modules/mocha/bin/mocha" in the build/ci section of the shippable.yml file that runs the tests. It gives no console feedback but outputs to the file speced in mochaFile option. Output locally appears to be correct?

**Comment by sumothecat** [comment]
If you run the command that's in the shippable.yml

    ./node_modules/mocha/bin/mocha --reporter mocha-junit-reporter -r ts-node/register ./api/**/*.ts --reporter-options mochaFile=shippable/testresults/testresults.xml

You get 91 test results in the XML output. But Shippable UI only reports 58.

**Comment by sumothecat** [comment]
Tested with manually-generated test output file in 8f02ec6874548d8a53d741d1cc30caa12639c776 - this file contains 3 tests and shippable shows 3 tests as expected.   https://app.shippable.com/github/jncc/catalog/runs/13/1/console

Can't find anything online about this issue.

**Comment by sumothecat** [comment]
Ran the tests locally, but simply copied the output file to the expected location. Correct count!
![shippable-test-count](https://user-images.githubusercontent.com/917606/31543641-f9a48b1a-b00e-11e7-86e7-bfe9ad75e77d.png)

**Comment by sumothecat** [comment]
Writing out the testresults.xml file with `cat` shows that the test command is really only producing 58 test results when run on Shippable.  https://app.shippable.com/github/jncc/catalog/runs/15/1/console

**Comment by sumothecat** [comment]
Fixed by changing the `files` argument to mocha to exclude the server.ts file  `"./api/**/!(server).ts"`. The problem was that the server.ts code was being running and starting up a node server there. Not sure how the build script didn't hang. Fixed in 8599705b32d27516591ff070b671b5c355ae5edd
91 tests running and passing, as expected in https://app.shippable.com/github/jncc/catalog/runs/16/1/console
